version: 1
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  timestamped:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
    filters: [evens_only]
  rotatingfile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: timestamped
    filename: loggymclogface.log
    maxBytes: 1024
    backupCount: 3
    filters: [evens_only]
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, rotatingfile]
    propagate: no
filters:
  evens_only:
    (): post_02.custom_filter.FibonacciFilter
root:
  level: DEBUG
  handlers: [console, rotatingfile]