version: 1
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  timestamped:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rotatingfile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: timestamped
    filename: loggymclogface.log
    maxBytes: 1024
    backupCount: 3
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, rotatingfile]
    propagate: no
root:
  level: DEBUG
  handlers: [console, rotatingfile]